### ISSUE TITLE
Typo:  PosrgreSQL should be PostgreSQL

### ISSUE THREAD

**Issue by gmagnenat** [zeroDevs/coding_challenge-13#115]
In the backend top 5 languages

**Comment by MattCSmith** [comment]
Nice catch, are you going to make this change or is this 'up for grabs'?

**Comment by gmagnenat** [comment]
this is up for grabs.

**Comment by leighd2008** [comment]
I created a pull request to fix this typo

**Comment by MattCSmith** [comment]
Closing as this was fixed in PR #116

**Comment by The24thDS** [comment]
@all-contributors add @gmagnenat for bug
