### ISSUE TITLE
Representation of small data on the chart

### ISSUE THREAD

**Issue by The24thDS** [zeroDevs/coding_challenge-13#118]
I propose that we rethink our approach on how the chart is handling these very small numbers. Currently is very hard to see the pie pieces. Maybe we should adjust the scale dynamically 🤔
![image](https://user-images.githubusercontent.com/26633429/51258020-9d459680-19b1-11e9-8c49-1db6c93fcd16.png)

**Comment by leighd2008** [comment]
@The24thDS I agree, are you working on this, or is it up for grabs?

**Comment by The24thDS** [comment]
I am not currently working on it :) It's free to fix 😄

**Comment by MattCSmith** [comment]
Sounds like a great idea :)
Are you taken this up @leighd2008

**Comment by aneagoie** [comment]
Just a heads up that we also want to do it in a way that the scale adjusts in an obvious way so that it's easy to compare job demand between the categories.

**Comment by leighd2008** [comment]
I will take this one on, I feel it is pushing the limits of what I know how to do.

**Comment by marcosandri-dev** [comment]
Just a maybe stupid question - why this has not the "assigned" like other issues?

**Comment by MattCSmith** [comment]
@marcosandri-dev This is something I spent about an hour trying to achieve before realising that you can only assign issues to either `members` of the organisation or the person whom opened the issue. At least from what I could figure out, Im not sure why its limited to this though :(

**Comment by leighd2008** [comment]
I made the scale of the Polar chart dynamic for better Representation of small data . I'm not sure how to make the change in scale more obvious, I'm open to suggestions.

**Comment by MattCSmith** [comment]
@The24thDS Do you think the recent changes have fixed this?

**Comment by aneagoie** [comment]
Hi, I think we should revert this change and keep the scale static as it is hard to see the relative difference between the technologies without a static scale.

**Comment by leighd2008** [comment]
I agree with @aneagoie. Does anyone know if it is possible to add a zoom feature (like on a map) to the Polar chart?

**Comment by The24thDS** [comment]
Can we keep the scale static but adjust it so the smaller values are more visible?

**Comment by leighd2008** [comment]
I'm not sure what you mean by that, the scale will have to change to make the smaller values more visible??

**Comment by The24thDS** [comment]
For the moment I think the best course of action here is to revert to the initial static scale as @aneagoie suggested.
