### ISSUE TITLE
Warning: Each child in an array or iterator should have a unique "key" prop. in App.js

### ISSUE THREAD

**Issue by leighd2008** [zeroDevs/coding_challenge-13#119]

**Comment by jakebolam** [comment]
The bot is having trouble with an invalid schema in the RC file, I've put up a PR to fix it: https://github.com/zeroDevs/coding_challenge-13/pull/181

Also going to improve the error message from the bot: https://github.com/all-contributors/all-contributors-bot/issues/102

**Comment by The24thDS** [comment]
@all-contributors add @leighd2008 for bug
