### ISSUE TITLE
Zero to Mastery Course Modal

### ISSUE THREAD

**Issue by MattCSmith** [zeroDevs/coding_challenge-13#126]
Perhaps it might be an idea to add a modal to the `Zero to Mastery` link in the `Brought to you by:` section in the footer. 

This would just be a small modal, with similar styling to the contributors modal, that has a brief description of the course/community, with a link to the Udemy course. Maybe even a link to all 3 course?

**Comment by aneagoie** [comment]
This feature is done correct?

**Comment by MattCSmith** [comment]
Nope, this is still up for grabs. 

I was thinking it would be cool that when you click on `Zero To Mastery` in the footer, rather than going straight to Udemy it would open a modal.
This modal would have a brief description on what ZTM is about and then perhaps three cards about each course thats available.

**Comment by jvdsouza** [comment]
If this is still up for grabs, I'm happy to take this on to do tomorrow.

**Comment by MattCSmith** [comment]
Sure its all yours @jvdsouza :)

**Comment by MattCSmith** [comment]
Hey @jvdsouza, How is this going?

**Comment by jvdsouza** [comment]
Hi @MattCSmith things have gotten a bit busy over the last couple of days but I've made sure to set time aside to get this done tomorrow. I've set myself up with some resources so I should be able to have it done within the next 2 days at most.

**Comment by MattCSmith** [comment]
Hey @jvdsouza No problem at all, was just checking in really, as I know how busy things can get sometimes :)

**Comment by MattCSmith** [comment]
Closing addressed in #193

**Comment by The24thDS** [comment]
@all-contributors add @jvdsouza for code
