### ISSUE TITLE
Update Fonts

### ISSUE THREAD

**Issue by MattCSmith** [zeroDevs/coding_challenge-13#127]
Maybe we can take a look at using/changing some fonts in the project. 
Making sure they are clean, crisp and easy to read.

Please add screenshots of all the fonts you change in your PR, so its easier to suggest any changes before merging.

**Comment by MattCSmith** [comment]
@mikeattara I do not have a particular font in mind, open to suggestions

**Comment by mikeattara** [comment]
Do you mind we use a monospace font?
I recommend `Roboto mono` which is accessible on Google fonts

**Comment by MattCSmith** [comment]
@mikeattara Sure that works for me

**Comment by mikeattara** [comment]
@MattCSmith I tried adding Roboto mono as the default font in PR #146 
Kindly review and let me know what you think.

**Comment by MattCSmith** [comment]
@mikeattara I like it, it looks great. 
Although perhaps there are a couple of things that need to be adjusted. But they could become thier own issue unless you want to address them.

1 - The developer love tool tip has no padding, and is looking pretty large. I dont remember it looking like this before, so its possible this didnt have much to do with the font change. 

2 - There are some left over font stylings from before in some of the CSS files.

Nice job on the choice of font 👍 What does everyone else think?

**Comment by MattCSmith** [comment]
Closing as addressed in #146 and #152, I'll take a look at making a few small tweaks as mentioned in #152
