### ISSUE TITLE
Dynamic chart title

### ISSUE THREAD

**Issue by MattCSmith** [zeroDevs/coding_challenge-13#129]
Lets make the chart title more descriptive, by dynamically changing it based on what tab the user has selected:

![image](https://user-images.githubusercontent.com/6190356/51323759-f6203800-1a60-11e9-9f75-1b9bef596a22.png)

They should read:

- Top 5 Web Technologies
- Top 5 Mobile Technologies
- Top 5 Programming Languages
- Top 5 Backend Technologies

**Comment by luxumbra** [comment]
I'd be happy to look at this.

**Comment by MattCSmith** [comment]
Hows this going @luxumbra?

**Comment by MattCSmith** [comment]
Closing as solved in #155

**Comment by luxumbra** [comment]
@MattCSmith I started looking in to it and got stuck and I've been on a mission with job hunting this week. Sorry! I'm going to pick it up again this evening.

**Comment by luxumbra** [comment]
Apologies for the poor communication on my part.
