### ISSUE TITLE
Consider all-contributors specification for this project 

### ISSUE THREAD

**Issue by mikeattara** [zeroDevs/coding_challenge-13#132]
I wish to suggest we consider all-contributors specification for the maintenance of this project. You can read more about it [here](https://github.com/all-contributors/all-contributors).

I have not done it before but would try my hands on that if the team accept this proposal.

**Comment by mikeattara** [comment]
@aneagoie @MattCSmith FYA

**Comment by aneagoie** [comment]
I think this is a great idea. Would love to see you implement this. What do you think @MattCSmith ?

**Comment by MattCSmith** [comment]
I agree would love to see this implemented.

Reading the documentation, I would suggest creating a contributors file, rather than doing so in the ReadMe.

Another option might also be to expand up the contributors modal, from the footer link?

**Comment by MattCSmith** [comment]
How's this going @mikeattara?

**Comment by MattCSmith** [comment]
No problem, I was following up to check on the state of some of the older issues. Did you still want to do this, or did you want me to put it `up for grabs`?

**Comment by mikeattara** [comment]
Kindly put the `up for grabs` tag for the main time...
I have to resolve some family issues for the time being. Thanks @MattCSmith

**Comment by MattCSmith** [comment]
No problem @mikeattara, hope everything works out for you

**Comment by MattCSmith** [comment]
mikeattara, thanks for all of your hard work, in general coding, bug fixes, questions, PR reviews, ideas and anything I may have missed 🤔 let's add mikeattara for his contributions @allcontributors[bot]

**Comment by MattCSmith** [comment]
mikeattara, thanks for all of your hard work, in general coding, bug fixes, questions, PR reviews, ideas and anything I may have missed 🤔 let's add @mikeattara for his contributions. cc @allcontributors[bot]

**Comment by The24thDS** [comment]
@allcontributors add @The24thDS for code

**Comment by jakebolam** [comment]
Thanks for the support!

@all-contributors add @The24thDS for code

^ Request above was missing the dash, I've ticked this here to add support, cc @The24thDS. https://github.com/all-contributors/all-contributors-bot/issues/99

The failures above where related to: https://github.com/all-contributors/all-contributors-bot/issues/16
We will get a fix for this out ASAP.

**Comment by jakebolam** [comment]
@all-contributors add @The24thDS for code

**Comment by The24thDS** [comment]
Thank you @jakebolam 😄

**Comment by MattCSmith** [comment]
Thanks for stopping by and helping us out with this @jakebolam. Fantastic support 👍

**Comment by The24thDS** [comment]
@all-contributors please add @AkinAguda for bug

**Comment by mikeattara** [comment]
@allcontributors[bot] add @jakebolam for support

**Comment by mikeattara** [comment]
@all-contributors please add @jakebolam for answers

**Comment by mikeattara** [comment]
@all-contributors please add @jakebolam for answers

**Comment by mikeattara** [comment]
@The24thDS Kindly merge #174 when ready and let's see if it works

**Comment by The24thDS** [comment]
Sure thing 😸

**Comment by The24thDS** [comment]
That would be `question` but I think I broke the bot by manually modifying `.all-contributossrc`

**Comment by jakebolam** [comment]
@MattCSmith just got online here. Mind giving me us a few hours to see if we can make it easier for existing projects? (Going to document it too)

**Comment by jakebolam** [comment]
Have put up a PR to fix your rc file: https://github.com/zeroDevs/coding_challenge-13/pull/181

**Comment by mikeattara** [comment]
@allcontributors[bot] please add @mikeattara for infra

**Comment by MattCSmith** [comment]
No problem at all @jakebolam, that would be fantastic 👍

**Comment by mikeattara** [comment]
I am ok with the state so far

**Comment by MattCSmith** [comment]
Oh there is alot more in the readme than I thought. We are still a little short though. 
I feel this either needs to be complete or removed though. We cant recognise half of the contributors there but no the other half.

I'll see if I can get some time to add some more

**Comment by mikeattara** [comment]
I will also try and add some more tomorrow

**Comment by The24thDS** [comment]
@all-contributors add @aneagoie for infra

**Comment by The24thDS** [comment]
@all-contributors add @MattCSmith for infra

**Comment by The24thDS** [comment]
We're up to date with the contributors' list.

**Comment by mikeattara** [comment]
Good job @The24thDS 
You are awesome

**Comment by MattCSmith** [comment]
Closing as fully implemented
