### ISSUE TITLE
Logo pops out when navbar toggled and resized

### ISSUE THREAD

**Issue by Feythelus** [zeroDevs/coding_challenge-13#142]
If you resize the window and toggle the navbar but then resize again without toggling again, the logo pops out and stays out until resized again and popped back in. (first issue ever so I hope this is good!) :)

![logofloatsifresized](https://user-images.githubusercontent.com/30155412/51433616-77afcb80-1c03-11e9-8abe-53207aa00026.png)
![navbarexpand](https://user-images.githubusercontent.com/30155412/51433617-78486200-1c03-11e9-8f95-f29b11e125e1.png)
![resizepopsoutlogo](https://user-images.githubusercontent.com/30155412/51433618-78486200-1c03-11e9-86ae-c004a69c98ac.png)

**Comment by Feythelus** [comment]
I've cloned it and built it in npm and I think was able to fix it by collapsing the logo with the navbar and putting a margin-left:auto on the nav toggler to keep it to the right.

![logopartofnav](https://user-images.githubusercontent.com/30155412/51433646-4be11580-1c04-11e9-87e9-c2e593f20b2e.png)
![logostaysinandcomesout](https://user-images.githubusercontent.com/30155412/51433647-4be11580-1c04-11e9-9a7c-9422a6e77370.png)

**Comment by MattCSmith** [comment]
Looks like a good fix @Feythelus, I have merged this 👍
