### ISSUE TITLE
Bug in the contributions count

### ISSUE THREAD

**Issue by MattCSmith** [zeroDevs/coding_challenge-13#156]
Each time you click on one of the technologies tabs (Web, mobile, languages and backend), the contributions count gets increased. 

![image](https://user-images.githubusercontent.com/6190356/51739951-aeb23100-208a-11e9-8995-9b19f3441fe4.png)

**Comment by The24thDS** [comment]
I think @MattCSmith hacked the contributions 😆

**Comment by mortenkos** [comment]
It updates contributions count every time it rerenders. Hardcoded contribution counts are added each time. I'm trying to figure out the best fix for this bug :)) Any help? :)

**Comment by The24thDS** [comment]
You could try using `React.memo`
[React v16.6](https://reactjs.org/blog/2018/10/23/react-v-16-6.html)

**Comment by mortenkos** [comment]
@The24thDS Thanks, React.memo() works perfectly I was going to implement shouldComponentUpdate() , but thanks for that tip :)

**Comment by The24thDS** [comment]
Nice 👍

**Comment by MattCSmith** [comment]
@mortenkos Can you tell me what Andrei's count is with your new code?

**Comment by mortenkos** [comment]
@MattCSmith Andrei's count is 93

**Comment by mortenkos** [comment]
@MattCSmith and yours 115

**Comment by MattCSmith** [comment]
Ok perfect, I noticed a slight issue that even on first load the count was incorrect.
I came up with another pretty simple solution, which I will share just for another option of what could have been done :), Although it could have done with some refactoring:

![image](https://user-images.githubusercontent.com/6190356/51772372-beaa2f00-20e3-11e9-8bcb-e41c3570ec44.png)

**Comment by MattCSmith** [comment]
But 93 and 115 is the correct count, so all is good :)

**Comment by mortenkos** [comment]
It was wrong on the first load because of state update and rerender after onscroll function

**Comment by MattCSmith** [comment]
Ah yeah that would make sense. 

Going to close this now its been resolved in #159

**Comment by The24thDS** [comment]
@all-contributors please add @The24thDS for question
