### ISSUE TITLE
Travis Fails to build due to eslint package

### ISSUE THREAD

**Issue by MattCSmith** [zeroDevs/coding_challenge-13#18]
Hey @mikeattara,

Could you kindly take a look at the issue reported around line 467 here:
https://travis-ci.org/zeroDevs/coding_challenge-13/builds/476501379

What would be the best resolution for this?

Regards
Matt

**Comment by mikeattara** [comment]
I have seen the problem solving it.

**Comment by MattCSmith** [comment]
Closing this, as issue has been resolved
