### ISSUE TITLE
toggler icon and logo display issue. 

### ISSUE THREAD

**Issue by luxumbra** [zeroDevs/coding_challenge-13#180]
The toggler icon markup has changed and now the icon displays irregular heights (probably down to the 1.5px height on the lines) and the icon is now rectangular.
![screenshot from 2019-01-26 15-00-20](https://user-images.githubusercontent.com/780350/51791373-dfcd5700-2199-11e9-8536-db01c03a6659.png)
![screenshot from 2019-01-26 14-59-44](https://user-images.githubusercontent.com/780350/51791374-dfcd5700-2199-11e9-9981-49d13bd6c368.png)

The site logo is now hidden on smaller screens and should display.

**Comment by The24thDS** [comment]
Thank you for your keen eye 👀 
@all-contributors please add @luxumbra for bug

**Comment by The24thDS** [comment]
@all-contributors please add @luxumbra for bug

**Comment by luxumbra** [comment]
Thanks @The24thDS :) I'm working on this now.

**Comment by The24thDS** [comment]
Closing. This has been resolved.
