### ISSUE TITLE
Developer Love - Data Sources: Description Box Misaligned

### ISSUE THREAD

**Issue by The24thDS** [zeroDevs/coding_challenge-13#184]
![image](https://user-images.githubusercontent.com/26633429/51792098-5b88cd00-21b5-11e9-896b-f022dbefc010.png)

**Comment by MattCSmith** [comment]
Hey @luxumbra,
As with the other issue just checking in on the status of this issue, with the upcoming deadline (see #200) is mind :)

Feel free to let me know if you need anything

**Comment by The24thDS** [comment]
Opps, I might have done this in #204 My bad
