### ISSUE TITLE
Remove the bot from contributors

### ISSUE THREAD

**Issue by The24thDS** [zeroDevs/coding_challenge-13#186]
The bot that we use for adding contributors is currently showing as a contributor 
> 🤖  AI will kill us 🤣 

![image](https://user-images.githubusercontent.com/26633429/51792251-27aea700-21b7-11e9-92cb-fa2fb9ae3220.png)
Someone can tweak with the contributors component in order to not include the bot

**Comment by mikeattara** [comment]
This issue has been resolved #194
