### ISSUE TITLE
for --> map or forEach inside dataExtractor function

### ISSUE THREAD

**Issue by dziukers** [zeroDevs/coding_challenge-13#19]
I would like to change for loop into map or forEach inside dataExstractor function.
1. If I remember correctly these methods are a little bit faster then looping.
2. It will look much clearer and simpler.

 What do you think?

**Comment by aneagoie** [comment]
the for loops is actually faster BUT, the code does look nicer with something like a map function. So go ahead with this. Sounds like a great idea!

**Comment by aneagoie** [comment]
https://github.com/zeroDevs/coding_challenge-13/pull/74Closing this now since it got fixed with

**Comment by The24thDS** [comment]
@all-contributors add @dziukers for ideas
