### ISSUE TITLE
Toolbox creates horizontal scroll bars

### ISSUE THREAD

**Issue by luxumbra** [zeroDevs/coding_challenge-13#191]
The toolbox controls don't resize when the browser is resized and thus create horizontal scroll bars.
![screenshot from 2019-01-26 20-12-17](https://user-images.githubusercontent.com/780350/51793356-19f92180-21b7-11e9-9e1e-e7303fb9a06e.png)

**Comment by The24thDS** [comment]
As far as I know, @mortenkos is currently working on this 😄

**Comment by luxumbra** [comment]
@The24thDS Ah ok. @mortenkos has beaten me to it ;) Does that make this a duplicate issue?

**Comment by MattCSmith** [comment]
What do you guys think about this for the toolbox?

Click `Launch demo modal sideout small`
https://bootsnipp.com/snippets/7ngvl

**Comment by The24thDS** [comment]
That would be fantastic @MattCSmith

**Comment by MattCSmith** [comment]
Ill create an issue for it, so someone can grab it

**Comment by MattCSmith** [comment]
@mortenkos Is this something you are working on?

**Comment by mortenkos** [comment]
@MattCSmith Yes I am :)

**Comment by MattCSmith** [comment]
Hey @mortenkos,
Just making my rounds to let everyone know of the deadline (see #200 )
Let me know if you need anything to get this issue close 😄

**Comment by The24thDS** [comment]
Good job on this one 👍
