### ISSUE TITLE
Slide out modal for the chart toolbox

### ISSUE THREAD

**Issue by MattCSmith** [zeroDevs/coding_challenge-13#192]
Create a slide out modal for the chart toolbox, as demonstrated here:
Click Launch demo modal sideout small
https://bootsnipp.com/snippets/7ngvl

here is the chat toolbox:
![image](https://user-images.githubusercontent.com/6190356/51794091-3602c000-21c3-11e9-891e-d23a5fd4e430.png)

**Comment by mortenkos** [comment]
Great idea guys :)
I was thinking something like this:
![screenshot from 2019-01-27 10-56-51](https://user-images.githubusercontent.com/25040343/51798909-a8ef5380-2222-11e9-95a7-28e8b4278934.png)

**Comment by MattCSmith** [comment]
@mortenkos I like this also 👍 
Ive you have the code for this, go ahead and make a PR :)

**Comment by mortenkos** [comment]
@MattCSmith  I have some adjustments to do and probably going to make PR tomorrow or at latest Tuesday. And it will be responsive

**Comment by The24thDS** [comment]
Let's try and add a magnifying glass instead of the Zoom words and also get the minus sign properly rotated @mortenkos

**Comment by MattCSmith** [comment]
I like this idea 👍 

@mortenkos, Just incase you miss my comment on the other issue:
```
Just making my rounds to let everyone know of the deadline (see #200 )
Let me know if you need anything to get this issue close 😄
```

**Comment by The24thDS** [comment]
We can close this now.

**Comment by The24thDS** [comment]
@all-contributors please add @mortenkos for ideas
