### ISSUE TITLE
SourceChart - value '16' of scale is overlapped

### ISSUE THREAD

**Issue by Dromediansk** [zeroDevs/coding_challenge-13#199]
![image](https://user-images.githubusercontent.com/34217538/51855243-1091c580-232d-11e9-97cb-9f7686d0c451.png)

I've noticed weird overlapping of number '16' in SourceChart component, which doesn't look pretty. I tried to adjust `padding `of  the component or `h3 `above it, but it didn't work. 
Has anyone suggestion, how could it be solved?

**Comment by MattCSmith** [comment]
I dont appear to see this issue, does this happen of every chart/source?

**Comment by danielyeoda** [comment]
PR is created. Do check it. Thank you

**Comment by The24thDS** [comment]
@all-contributors please add @Dromediansk for bug

**Comment by The24thDS** [comment]
Addressed in #211
