### ISSUE TITLE
Setup linting

### ISSUE THREAD

**Issue by mikeattara** [zeroDevs/coding_challenge-13#2]
I want to setup linting for the project so that, the format will be consistent.  FYA @aneagoie @MattCSmith @thisisabdus @anantankur 
Should I go ahead?

**Comment by aneagoie** [comment]
Absolutely. A great way to start off the project! Please go ahead with it.

**Comment by mikeattara** [comment]
@aneagoie What do you think about using airbnb style and setting up prettier?

**Comment by aneagoie** [comment]
That is exactly what I like using on my project (or sometimes standard). I think that's a great choice moving forward. Perhaps 2 PRs? Start with prettier?

**Comment by mikeattara** [comment]
Thanks, @aneagoie. I will close this issue now.
