### ISSUE TITLE
Small devices layout

### ISSUE THREAD

**Issue by peacethekuma** [zeroDevs/coding_challenge-13#209]
![clip](https://user-images.githubusercontent.com/37570898/51881530-8c842000-23b6-11e9-98a6-b5c00f7ee7f4.PNG)
I think layout in small device needs a fix, I am working on this :laughing:

**Comment by The24thDS** [comment]
@all-contributors please add @peacethekuma for bug

**Comment by The24thDS** [comment]
Addressed this in #257

**Comment by MattCSmith** [comment]
Closing as addressed in #257
