### ISSUE TITLE
Add shadow property to the trend box/container

### ISSUE THREAD

**Issue by arudovwen** [zeroDevs/coding_challenge-13#23]
i'd like to add shadow property to the trend box.

**Comment by arudovwen** [comment]
and probably the navigation too, looks nicer with it

**Comment by arudovwen** [comment]
i noticed the language nav overlapping between 573 and 769px breakpoint

**Comment by arudovwen** [comment]
im not really good with travis, but it seems 1 commit passed and 2 failed, right?

**Comment by MattCSmith** [comment]
Hey @arudovwen,
The Travis issue should now have been resolved. It was having issues with the version of eslint.

**Comment by The24thDS** [comment]
@all-contributors add @arudovwen for ideas
