### ISSUE TITLE
Add an active class to the sub nav items

### ISSUE THREAD

**Issue by MattCSmith** [zeroDevs/coding_challenge-13#40]
The sub nav items could use an active class, so it shows which tab is currently being displayed:
Something like this:
![image](https://user-images.githubusercontent.com/6190356/50838121-30008880-1355-11e9-9c86-6f81bdae37db.png)

**Comment by mikeattara** [comment]
@MattCSmith add up-for-grabs label

**Comment by The24thDS** [comment]
Implemented in #45

**Comment by aneagoie** [comment]
Well done, closing this issue
