### ISSUE TITLE
Add a temporary scrollbar

### ISSUE THREAD

**Issue by Pawelv9** [zeroDevs/coding_challenge-13#52]
I have thoughts to add a temporary scrollbar attached to `body` tag instead of a standard scrollbar
Will be something like this
![screenshot 609](https://user-images.githubusercontent.com/15182822/50872047-f5d3cd00-13ce-11e9-8d46-35ff2ab9a911.png)

**Comment by MattCSmith** [comment]
I like it 👍 Go ahead, implement it and make a PR :)

**Comment by The24thDS** [comment]
@all-contributors add @Pawelv9 for ideas
