### ISSUE TITLE
Adding hover effects on anchor tags in footer component

### ISSUE THREAD

**Issue by Vectormike40** [zeroDevs/coding_challenge-13#60]
It's my first Open source contribution. Can I add hover effect in the footer component?

**Comment by aneagoie** [comment]
Sounds like a great idea! I'm excited for your first contribution!

**Comment by MattCSmith** [comment]
Closing this issue, as it was addressed in PR https://github.com/zeroDevs/coding_challenge-13/pull/59/files

**Comment by The24thDS** [comment]
@all-contributors add @Vectormike40 for code, ideas
