### ISSUE TITLE
Chart tool tips styles do not match

### ISSUE THREAD

**Issue by MattCSmith** [zeroDevs/coding_challenge-13#65]
The tooltip for the chart in the `how we get our data section` could probably use some adjusting so that it looks more like the one at the top of the page.

So from this:
![image](https://user-images.githubusercontent.com/6190356/50906546-44a85380-141d-11e9-9f63-999856b7715f.png)

To this:
![image](https://user-images.githubusercontent.com/6190356/50906603-5be74100-141d-11e9-867f-ca5574af678a.png)

**Comment by luxumbra** [comment]
I'll take this, if that's OK?
