### ISSUE TITLE
Better checkbox allignment on smaller screens

### ISSUE THREAD

**Issue by MattCSmith** [zeroDevs/coding_challenge-13#66]
These checkbox could use some further styling to make them align nicer on smaller devices:
![image](https://user-images.githubusercontent.com/6190356/50907095-7241cc80-141e-11e9-9acc-0ac2303a2e37.png)

**Comment by luxumbra** [comment]
I'd like to take this as my first contribution.

**Comment by aneagoie** [comment]
Go for it @luxumbra :)
