### ISSUE TITLE
Chart size on smaller screens

### ISSUE THREAD

**Issue by MattCSmith** [zeroDevs/coding_challenge-13#67]
The chart in `data` section could use some further styling to make it just a little larger on smaller devices. So that its similar in size to the one in the `how we get out data` section.

Data Section:
![image](https://user-images.githubusercontent.com/6190356/50907334-001db780-141f-11e9-95bc-ea3f65470b13.png)

How we get our data section:
![image](https://user-images.githubusercontent.com/6190356/50907384-217ea380-141f-11e9-8506-95d4dd9df17b.png)
(this could also use a little padding so it doesnt reach the box edges)

**Comment by GlynL** [comment]
I've coincidentally worked on this by applying the legend on touch devices. #53
