### ISSUE TITLE
How to join the discord channel?

### ISSUE THREAD

**Issue by joe-ging** [zeroDevs/coding_challenge-13#7]
Seems I need something that starts with https?
![screen shot 2019-01-08 at 12 32 04 am](https://user-images.githubusercontent.com/23192885/50780029-deb4b280-12dc-11e9-8085-915a700b39d6.png)

**Comment by aneagoie** [comment]
You need to go to lesson 3 of the Udemy course and click on the link there as the server is only for enrolled students
