### ISSUE TITLE
Newsletter signup button - Entering Email and clicking button just spins

### ISSUE THREAD

**Issue by porschefish** [zeroDevs/coding_challenge-13#99]

**Comment by porschefish** [comment]
Operating System: Windows 10
Browser: Firefox 64.0.2 (64-bit)
Steps:
1. From the main page (https://zerodevs.github.io/coding_challenge-13/), scroll down to the "Get Monthly Email Report" section. 
2. Enter your email.
3. Click the Subscribe button.
4. The button text changes to a spinning animation and never provides any feedback.

**Comment by aneagoie** [comment]
Here is how we can fix it... perhaps someone can do a PR for this @mikeattara or @porschefish :

```
Insert the following snippet of JavaScript on every page of your website right before the closing </head> tag.

Please note: You only need to add this snippet once, even if you plan to have a few different forms. There is no need to insert this JavaScript snippet if you already have it on your website.


<!-- MailerLite Universal -->
<script>
(function(m,a,i,l,e,r){ m['MailerLiteObject']=e;function f(){
var c={ a:arguments,q:[]};var r=this.push(c);return "number"!=typeof r?r:f.bind(c.q);}
f.q=f.q||[];m[e]=m[e]||f.bind(f.q);m[e].q=m[e].q||f.q;r=a.createElement(i);
var _=a.getElementsByTagName(i)[0];r.async=1;r.src=l+'?v'+(~~(new Date().getTime()/1000000));
_.parentNode.insertBefore(r,_);})(window, document, 'script', 'https://static.mailerlite.com/js/universal.js', 'ml');

var ml_account = ml('accounts', '1252504', 'i9w0t9r0s7', 'load');
</script>
<!-- End MailerLite Universal -->

Copy to clipboard
Copy and paste the code provided below, wherever you want the form to appear.

<div class="ml-form-embed"
  data-account="1252504:i9w0t9r0s7"
  data-form="1154434:v3f5g7">
</div>

```

**Comment by mikeattara** [comment]
@porschefish Kindly claim this.

**Comment by porschefish** [comment]
Thanks @aneagoie @MattCSmith and @mikeattara,
I am still in the middle of section 13 (advanced Javascript) in the Zero to Mastery course, so my git skills are still very limited. I do recall a little bit of git from the end of section 8, but I bet I need to complete section 16 of the course before I can do much more than report bugs. I am fine if somebody else would like to take this one.
Thanks!

**Comment by MattCSmith** [comment]
Closing, as this PR addresses this issue:
https://github.com/zeroDevs/coding_challenge-13/pull/107

**Comment by MattCSmith** [comment]
This issue, does not appear to have been solved with PR: 107

**Comment by jeremyfox36** [comment]
I tried moving the mailerlite script up to just before the closing head tag of index.html like Andrei suggested - it didn't work though :\
When you press the submit button, the error in the console says:
![image](https://user-images.githubusercontent.com/9820406/51213229-5d7ba200-1912-11e9-8a6e-1dc7d09d30f5.png)
I'll have another look at it tomorrow.

**Comment by MattCSmith** [comment]
@jeremyfox36 Thanks for taking a look at this :)
Your screenshot actually helped me figure out the issue and I have the answer to fix it.
However, If you would like to solve it for your self, I will hold back on providing the answer?

**Comment by jeremyfox36** [comment]
@MattCSmith no worries, but I'd like to try and solve this one please.  I won't leave you hanging too long though so I'll spend an hour on it this evening and then admit defeat (I'm on UK time by the way).

**Comment by MattCSmith** [comment]
@jeremyfox36 Awesome, its no problem at all, take your time. Let me know if you need a hint or any help :)

**Comment by otanriverdi** [comment]
@jeremyfox36 Although I am not entirely sure, I may have a solution. Let me know if you need help and we can work on it together through discord.

**Comment by MattCSmith** [comment]
@jeremyfox36 As Mike mentioned in your PR, this actually made the form disappear. There is a pretty simple fix for this also, if you wanted to take that on?

**Comment by jeremyfox36** [comment]
Ok - cool. I noticed that about the form, but the problem seemed intermittent and the form came back when I refreshed the page. I’ll have another go today.

**Comment by MattCSmith** [comment]
Closing as this was fixed

**Comment by The24thDS** [comment]
@all-contributors add @jeremyfox36 for code

**Comment by The24thDS** [comment]
@all-contributors add @aneagoie for question

**Comment by The24thDS** [comment]
@all-contributors add @porschefish for bug
